=== RayWang1991/miniSpring/src/test/resources/schema/mySpring.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://indi.ray.miniSpring"
           targetNamespace="http://indi.ray.miniSpring">
    <!--elementFormDefault="qualified">-->

    <xs:element name="value" type="xs:string">
    </xs:element>

    <xs:element name="ref">
        <xs:complexType>
            <xs:complexContent mixed="true">
                <xs:restriction base="xs:anyType">
                    <xs:attribute name="bean" type="xs:string"/>
                </xs:restriction>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="null" type="xs:string"/>

    <xs:element name="integer">
        <xs:simpleType>
            <xs:restriction base="xs:int">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="100"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:group name="collectionSubElements">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="list"/>
                <xs:element ref="map"/>
                <xs:element ref="set"/>
                <xs:element ref="value"/>
                <xs:element ref="null"/>
                <xs:element ref="ref"/>
                <xs:element ref="bean"/>
            </xs:choice>
        </xs:sequence>
    </xs:group>

    <xs:element name="key" type="xs:string"/>
    <xs:element name="entry">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="1">
                <xs:element ref="key"/>
                <xs:group ref="collectionSubElements"/>
            </xs:sequence>
            <xs:attribute name="key" type="xs:string"/>
            <xs:attribute name="key-ref" type="xs:string"/>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="value-ref" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="map">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="entry"/>
            </xs:sequence>
            <xs:attribute name="key-type" type="xs:string">
                <xs:annotation>
                    <xs:documentation>
                        <![CDATA[
                        表示map的key的类型
                        ]]>
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="list">
        <xs:complexType>
            <xs:group ref="collectionSubElements"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="set">
        <xs:complexType>
            <xs:group ref="collectionSubElements"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="id" type="xs:string"/>


    <xs:complexType name="typeWithId" abstract="true">
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <!--beanAttribute-->
    <xs:attributeGroup name="beanAttribute">
        <xs:attribute name="name" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    <![CDATA[
                    bean的beanName，用作唯一标识bean，如为空，则在xml中不可引用bean。bean的名称则为类名+#编号
                    ]]>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>

        <xs:attribute name="class" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation source="java:java.lang.Class"><![CDATA[
	The fully qualified name of the bean's class, except if it serves only
	as a parent definition for child bean definitions.
				]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>

        <xs:attribute name="autowired" default="default">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="default"/>
                    <xs:enumeration value="no"/>
                    <xs:enumeration value="byName"/>
                    <xs:enumeration value="byType"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>

        <xs:attribute name="depends-on" type="xs:string">
        </xs:attribute>

        <xs:attribute name="primary" type="xs:boolean" default="false"/>

        <xs:attribute name="lazy-init" type="xs:boolean" default="false"/>

        <xs:attribute name="scope" default="singleton">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="singleton"/>
                    <xs:enumeration value="prototype"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>

    </xs:attributeGroup>

    <!--beanElements-->

    <xs:element name="property">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="1">
                <xs:element ref="bean"/>
                <xs:element ref="ref"/>
                <xs:element ref="value"/>
                <xs:element ref="null"/>
                <xs:element ref="list"/>
                <xs:element ref="set"/>
                <xs:element ref="map"/>
            </xs:choice>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="value-ref" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="constructor-arg">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element ref="bean"/>
                <xs:element ref="ref"/>
                <xs:element ref="value"/>
                <xs:element ref="null"/>
                <xs:element ref="list"/>
                <xs:element ref="set"/>
                <xs:element ref="map"/>
            </xs:choice>
            <xs:attribute name="index" type="xs:int"/>
            <xs:attribute name="type" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:group name="beanElements">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="property"/>
                <xs:element ref="constructor-arg"/>
            </xs:choice>
        </xs:sequence>
    </xs:group>

    <xs:element name="bean">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="typeWithId">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:group ref="beanElements"/>
                    </xs:sequence>
                    <xs:attributeGroup ref="beanAttribute"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="beans">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="bean"/>
            </xs:sequence>
            <xs:attribute name="default-autowire" default="byName">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="no"/>
                        <xs:enumeration value="byName"/>
                        <xs:enumeration value="byType"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RayWang1991/miniSpring/src/test/resources/proxyFactoryBeanTest/beanNameAutoProxyCreatorTest1.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://indi.ray.miniSpring"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://indi.ray.miniSpring /Users/raywang/IdeaProjects/miniSpring/src/test/resources/schema/mySpring.xsd"
       default-autowire="byName">
    <bean id="logInterceptor" class="indi.ray.miniSpring.aop.functionTest.proxySetUp.MethodLoggerInterceptor"/>
    <bean id="performInterceptor" class="indi.ray.miniSpring.aop.functionTest.proxySetUp.MethodPerformanceInterceptor"/>
    <bean id="nameRecorder" class="java.util.ArrayList"/>
    <bean id="normRecorderInterceptor"
          class="indi.ray.miniSpring.aop.functionTest.proxySetUp.MethodNameRecordInterceptor">
        <constructor-arg>
            <ref>nameRecorder</ref>
        </constructor-arg>
    </bean>

    <bean id="doubleRecorderInterceptor"
          class="indi.ray.miniSpring.aop.functionTest.proxySetUp.MethodNameDoubleRecordInterceptor">
        <constructor-arg>
            <ref>nameRecorder</ref>
        </constructor-arg>
    </bean>


    <bean id="student" class="indi.ray.miniSpring.aop.Student"/>

    <bean class="indi.ray.miniSpring.aop.autoProxyCreator.BeanNameAutoProxyCreator">
        <property name="interceptorNames">
            <list type="java.lang.String">
                <value>logInterceptor</value>
                <value>performInterceptor</value>
                <value>normRecorderInterceptor</value>
                <value>doubleRecorderInterceptor</value>
            </list>
        </property>
        <property name="beanNames">
            <list type="java.lang.String">
                <value>student</value>
            </list>
        </property>
    </bean>

</beans>

=== RayWang1991/miniSpring/src/test/resources/proxyFactoryBeanTest/proxyFactoryBeanBasic.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://indi.ray.miniSpring"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://indi.ray.miniSpring /Users/raywang/IdeaProjects/miniSpring/src/test/resources/schema/mySpring.xsd"
       default-autowire="no">
    <bean id="logInterceptor" class="com.ray.miniSpring.aop.functionTest.proxySetUp.MethodLoggerInterceptor"/>
    <bean id="performInterceptor" class="com.ray.miniSpring.aop.functionTest.proxySetUp.MethodPerformanceInterceptor"/>
    <bean id="nameRecorder" class="java.util.ArrayList"/>
    <bean id="normRecorderInterceptor"
          class="com.ray.miniSpring.aop.functionTest.proxySetUp.MethodNameRecordInterceptor">
        <constructor-arg>
            <ref>nameRecorder</ref>
        </constructor-arg>
    </bean>

    <bean id="doubleRecorderInterceptor"
          class="com.ray.miniSpring.aop.functionTest.proxySetUp.MethodNameDoubleRecordInterceptor">
        <constructor-arg>
            <ref>nameRecorder</ref>
        </constructor-arg>
    </bean>


    <bean id="student_target" class="com.ray.miniSpring.aop.Student"/>

    <bean id="student1" class="com.ray.miniSpring.aop.proxy.ProxyFactoryBean">
        <property name="interceptorNames">
            <list type="java.lang.String">
                <value>logInterceptor</value>
            </list>
        </property>
        <property name="target" value-ref="student_target"/>
    </bean>

    <bean id="student2" class="com.ray.miniSpring.aop.proxy.ProxyFactoryBean">
        <property name="interceptorNames">
            <list type="java.lang.String">
                <value>normRecorderInterceptor</value>
                <value>doubleRecorderInterceptor</value>
            </list>
        </property>
        <property name="target" value-ref="student_target"/>
    </bean>

    <bean id="doubleRecorderInterceptor_prototype"
          scope="prototype"
          class="com.ray.miniSpring.aop.functionTest.proxySetUp.MethodNameDoubleRecordInterceptor">
        <constructor-arg>
            <ref>nameRecorder</ref>
        </constructor-arg>
    </bean>


    <bean id="student3" class="com.ray.miniSpring.aop.proxy.ProxyFactoryBean" scope="prototype">
        <property name="interceptorNames">
            <list type="java.lang.String">
                <value>normRecorderInterceptor</value>
                <value>doubleRecorderInterceptor_prototype</value>
            </list>
        </property>
        <property name="target" value-ref="student_target"/>
    </bean>
</beans>

=== RayWang1991/miniSpring/src/test/resources/xmlTest/loadTest3.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://indi.ray.miniSpring"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://indi.ray.miniSpring /Users/raywang/IdeaProjects/miniSpring/src/test/resources/schema/mySpring.xsd"
       default-autowire="byName">
    <bean id="obj" class="java.lang.String"/>
    <bean id="pojo" class="indi.ray.miniSpring.core.functionTest.xml.basic.PoJoTestBean"/>
    <bean id="constructorTestBean1"
          class="indi.ray.miniSpring.core.functionTest.xml.basic.ConstructorTestBean">
        <constructor-arg>
            <ref>obj</ref>
        </constructor-arg>
        <constructor-arg>
            <ref>pojo</ref>
        </constructor-arg>
    </bean>
    <bean id="constructorTestBean2"
          class="indi.ray.miniSpring.core.functionTest.xml.basic.ConstructorTestBean">
        <constructor-arg>
            <ref>obj</ref>
        </constructor-arg>
        <constructor-arg>
            <ref>pojo</ref>
        </constructor-arg>
        <constructor-arg>
            <value>10</value>
        </constructor-arg>
    </bean>
    <bean id="constructorTestBean3"
          class="indi.ray.miniSpring.core.functionTest.xml.basic.ConstructorTestBean">
        <constructor-arg>
            <ref>obj</ref>
        </constructor-arg>
        <constructor-arg>
            <value>stringValue</value>
        </constructor-arg>
    </bean>
    <bean id="constructorTestBean4"
          class="indi.ray.miniSpring.core.functionTest.xml.basic.ConstructorTestBean">
        <constructor-arg>
            <list type="java.lang.Object">
                <value>obj</value>
            </list>
        </constructor-arg>
        <constructor-arg>
            <list type="int">
                <value>1</value>
                <value>2</value>
                <value>3</value>
            </list>
        </constructor-arg>
    </bean>
    <bean id="constructorTestBean5"
          class="indi.ray.miniSpring.core.functionTest.xml.basic.ConstructorTestBean">
        <constructor-arg >
            <value>1</value>
        </constructor-arg>
    </bean>
    <bean id="constructorTestBean6"
          class="indi.ray.miniSpring.core.functionTest.xml.basic.ConstructorTestBean">
        <constructor-arg >
            <list type="java.lang.Integer">
                <value>1</value>
            </list>
        </constructor-arg>
    </bean>
    <bean id="constructorTestBean7"
          class="indi.ray.miniSpring.core.functionTest.xml.basic.ConstructorTestBean">
        <constructor-arg>
            <set type="java.lang.String">
                <value>1</value>
                <value>2</value>
                <value>3</value>
            </set>
        </constructor-arg>
    </bean>
</beans>

=== RayWang1991/miniSpring/src/test/resources/xmlTest/loadTest1.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://indi.ray.miniSpring"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://indi.ray.miniSpring /Users/raywang/IdeaProjects/miniSpring/src/test/resources/schema/mySpring.xsd"
       default-autowire="byName">
    <bean id="pojo1" class="com.ray.miniSpring.core.functionTest.xml.basic.PoJoTestBean"/>
    <bean class="com.ray.miniSpring.core.functionTest.xml.basic.PoJoTestBean"/>
    <bean id="pojo2" class="com.ray.miniSpring.core.functionTest.xml.basic.PoJoTestBean"/>
    <bean id="constructorTestBean" class="com.ray.miniSpring.core.functionTest.xml.basic.ConstructorTestBean">
        <constructor-arg type="java.lang.Object" index="0">
            <ref>pojo1</ref>
        </constructor-arg>
        <constructor-arg type="com.ray.miniSpring.core.functionTest.xml.basic.PoJoTestBean" index="1">
            <ref>pojo2</ref>
        </constructor-arg>
    </bean>
</beans>
